### ISSUE TITLE
Cannot find gem

### ISSUE THREAD

**Issue by javiervg** [nicolasblanco/sweet-alert2-rails#1]
Hello Nicolas,

Was hoping to evaluate your gem which seems like a great implementation of sweet-alert2. However, it was not found in any repository.

ERROR:  Could not find a valid gem 'sweet-alert2-rails' (>= 0) in any repository

Javier

**Comment by nicolasblanco** [comment]
Try to check from the master branch from now:

`gem 'sweet-alert2-rails', github: 'nicolasblanco/sweet-alert2-rails'`

I'll push this gem soon, thanks.

**Comment by javiervg** [comment]
Awesome thanks Nicolas,
Javier

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 29, 2016 at 5:49 PM, Nicolas Blanco<notifications@github.com> wrote:   
Try to check from the master branch from now:

gem 'sweet-alert2-rails', github: 'nicolasblanco/sweet-alert2-rails'

I'll push this gem soon, thanks.

**Comment by nicolasblanco** [comment]
I've just published it on rubygems.
